//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioPractico
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaCliente
    {
        public int CajaClienteID { get; set; }
        public int CajaID { get; set; }
        public int ClienteID { get; set; }
        public int EstadoCajaClienteID { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoCajaCliente EstadoCajaCliente { get; set; }
    }
}
